# -*- coding: utf-8 -*-
"""Emotion_LSTM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PV3Ef9NH3K08rmkGfxNxGosfKSHF_aSj

import libraries
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

"""Loading Data"""

from google.colab import drive

drive.mount("/content/drive/")

# Commented out IPython magic to ensure Python compatibility.
# %cd "/content/drive/MyDrive"

data = pd.read_csv('emotions.csv')

data.head()

data['label'].value_counts()

data.info()

label_maping = {'NEGATIVE': 0, 'NEUTRAL': 1, 'POSITIVE': 2}

data['label'] = data['label'].replace(label_maping)

data.head()

X = data.drop('label', axis=1)
y = data['label']

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X = scaler.fit_transform(X)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)

print('Shape X_Train:', X_train.shape)
print('Shape y_Train:', y_train.shape)
print('Shape X_Test:', X_test.shape)
print('Shape y_Test:', y_test.shape)

# X_train = X_train.reshape(X_train, (1492,1, 2548))
# X_test = X_test.reshape(X_test, (640,1,2548))
X_train = X_train.reshape(-1, 1, 2548)
X_test = X_test.reshape(-1, 1, 2548)

import tensorflow as tf
from keras.models import Sequential
from keras.layers import Dense, LSTM, Dropout
from keras.optimizers import Adam

model = Sequential()
model.add(LSTM(64, activation='relu', input_shape=(1, 2548), return_sequences=True))
model.add(Dropout(0.2))
model.add(LSTM(32, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(3, activation='softmax'))

model.summary()

model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

model.fit(X_train, y_train, epochs=200, batch_size=32, validation_data=(X_test, y_test))

y_pred_proba = model.predict(X_test)

y_pred_proba[10]

predict_labels = np.argmax(y_pred_proba, axis=1)

y_pred = predict_labels

y_pred[10]

from sklearn.metrics import confusion_matrix, classification_report

print(confusion_matrix(y_test, y_pred))

cm = confusion_matrix(y_test, y_pred)

sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')

print(classification_report(y_test, y_pred))

