# -*- coding: utf-8 -*-
"""Object_Detection(YOLO_V5).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i5n23rsnjIiNCh8lJGoNPXwcg3jozD5v
"""

from google.colab import drive

drive.mount('/content/drive', force_remount=True)

!pip install tensorflow
!pip install tensorboard
!pip install torch

!git clone https://github.com/ultralytics/yolov5

# Commented out IPython magic to ensure Python compatibility.
# %cd yolov5

"""Part 1 : Using Pre-trained model"""

!pip install -r requirements.txt

!ls /content/drive/MyDrive/

!ls /content/drive/MyDrive/image_one.jpg

!ls /content/drive/MyDrive/ | grep -i image

# !python detect.py --weights yolov5s.pt --source /content/drive/MyDrive/image_one.jpg
!python detect.py --weights yolov5s.pt --img 640 --conf 0.25 --source "/content/drive/MyDrive/image_one.jpg" --exist-ok --save-crop

from IPython.display import Image
Image('runs/detect/exp/image_one.jpg')

!ls runs/detect/exp/crops/
!display runs/detect/exp/crops/person/*.jpg

!python detect.py --weights yolov5s.pt --source "/content/drive/MyDrive/" --exist-ok --save-crop

from IPython.display import Image, display
import glob

person_crops = glob.glob('runs/detect/exp/crops/person/*.jpg')
for img_path in sorted(person_crops):
    print(img_path)
    display(Image(filename=img_path))

bicycle_crops = glob.glob('runs/detect/exp/crops/bicycle/*.jpg')
for img_path in sorted(bicycle_crops):
    display(Image(filename=img_path))

car_crops = glob.glob('runs/detect/exp/crops/car/*.jpg')
for img_path in sorted(car_crops):
    display(Image(filename=img_path))

motor_crops = glob.glob('runs/detect/exp/crops/motorcycle/*.jpg')
for img_path in sorted(motor_crops):
    display(Image(filename=img_path))

!python detect.py --weights yolov5s.pt --img 640 --conf-thres 0.7 --source "/content/drive/MyDrive/image_one.jpg" --exist-ok --save-crop

from IPython.display import Image
Image('runs/detect/exp/image_one.jpg')

!python detect.py --weights yolov5s.pt --img 640 --conf-thres 0.7 --source "/content/drive/MyDrive/image_two.jpg" --exist-ok --save-crop

from IPython.display import Image
Image('runs/detect/exp/image_two.jpg')

!python detect.py --weights yolov5s.pt --img 640 --conf-thres 0.7 --source "/content/drive/MyDrive/car.mp4" --exist-ok --save-crop

from IPython.display import Video, display
display(Video("/content/drive/MyDrive/YOLO_Results/car_video_result/car.mp4", embed=True, width=800))

!python detect.py --weights yolov5s.pt --img 640 --conf-thres 0.7 --source "/content/drive/MyDrive/image_two.jpg" --classes 0 1

from IPython.display import Image
Image('runs/detect/exp/image_one.jpg')

